### ISSUE TITLE
MacOS Command key for Zellij keybindings

### ISSUE THREAD

**Issue by erikkrieg** [erikkrieg/.dotfiles#11]
I'd rather use Command than Ctrl for Zellij keybinds but currently it doesn't seem to support this key. Some issues on the topic:
- https://github.com/zellij-org/zellij/issues/1042
- https://github.com/zellij-org/zellij/issues/1343

In order to do this it seems like it would probably require a contribution to their project.

**Comment by erikkrieg** [comment]
While I don't love it, I think that binding some command modified keys to control in Alacritty is the best I can do for now.

Change is: https://github.com/erikkrieg/.dotfiles/commit/ea5b666d158d3fd17b33f0efaf20dc17a6690574

**Comment by saward** [comment]
@erikkrieg Thanks very much for linking to the actual config you used!

**Comment by erikkrieg** [comment]
> @erikkrieg Thanks very much for linking to the actual config you used!

Glad I was able to help!
